apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: k8s
    repoURL: https://github.com/vfarcic/1-koncrete-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true

